packages:
  - 'website'
  - 'sdk/js'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js
  - esbuild
  - vue-demi
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true
